# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[ja]
 languageCode = "ja-jp"
 contentDir = "content/ja"
 title = "日本語版だよ"
 [ja.params]
   description = "日本語の説明だよ"

[[ja.menu.main]]
  name = "ホーム"
  url = "#about"
  weight = 10

[[ja.menu.main]]
  name = "投稿"
  url = "#posts"
  weight = 20

[[ja.menu.main]]
  name = "プロジェクト"
  url = "#projects"
  weight = 30

[[ja.menu.main]]
  name = "フィーチャード"
  url = "#featured"
  weight = 40

[[ja.menu.main]]
  name = "コンタクト"
  url = "#contact"
  weight = 60
